### ISSUE TITLE
多言語では音声認識の挙動が異なる

### ISSUE THREAD

**Issue by asahi-abc** [jphacks/NG_2305#3]
# 問題
英語以外ではSpeechRecognizerの`shouldReportPartialResults`の挙動が異なるため、画面の表示がおかしくなる。
さらに、一瞬だけ予測が英語で出ている。

# 参考動画
![trim 746FD71B-D6BF-4C3B-9E96-E001A3A6A51E](https://github.com/jphacks/NG_2305/assets/109562639/52917a26-91e4-4e2e-8326-b701ff4e80a7)

# 原因
現在、英語の認識の際には、単語間の空白でリセットの判定を行なっているが、日本語では途中経過が単語ごとではなく、さらに細分化されていることが原因と考えられる。
予測が英語で出てしまうのは、プロンプトが英語で設定してあることが原因と考えられる。

**Comment by hikaruaohara** [comment]
@asahi-abc 
日本語で試してみたけど、日本語の場合は一度話した内容が削除されずに毎回ちゃんと認識結果として出力されるっぽいね。

**Comment by asahi-abc** [comment]
# 変更点
### 言語問わず
`request.shouldReportPartialResults = true`の場合、途中結果と最終結果が出力されるが、画面をタップした時に最終結果が確定するようになっている。以前は、時間経過で最終結果も出力されていた。

```
Hello 
Hello this
Hello this is
Hello this is the
Hello this is the first
Hello this is the first sent
Hello this is the first sentence //ここまでは途中結果
Hello this is the first sentence //画面をタップすると出力される最終結果
```

### 日本語
音声認識が単語単位でなく、文字単位なので`request.shouldReportPartialResults = true`だと表示が変に見える。
```
こ
こん
こんに
こんにち
こんにちはにち
こんにちは
こんにちは私
こんにちは私は //途中結果
こんにちは私は //画面をタップ
```
